# Generated by Django 6.0.5 on 2026-05-17 11:24

import cargohandling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargohandling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['brand', 'model', 'year'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['name'], 'verbose_name': 'Вид транспортного средства', 'verbose_name_plural': 'Виды транспортных средств'},
        ),
        migrations.RemoveField(
            model_name='cargotype',
            name='requires_refrigeration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cargo_weight_kg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='max_load_kg',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, help_text='Банковские реквизиты, УНП и т.д.', verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargohandling.bodytype', verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Полный текст статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снять галочку, чтобы скрыть новость', verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(help_text='Одно предложение, которое видно в списке новостей', max_length=500, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='cargotype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название груза'),
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargohandling.organization'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[cargohandling.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='companyhistory',
            name='event',
            field=models.TextField(help_text='Что произошло в этом году', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(help_text='Основной текст о компании', verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[cargohandling.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube или Vimeo ссылка', verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, help_text='Что делает сотрудник', verbose_name='Описание / обязанности'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (29) XXX-XX-XX', max_length=20, validators=[cargohandling.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_category',
            field=models.CharField(default='B', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50, verbose_name='Номер ВУ'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, validators=[cargohandling.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargohandling.cargotype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargohandling.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='distance_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargohandling.driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='cargohandling.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargohandling.vehicle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=20, validators=[cargohandling.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(help_text='Например: SUMMER2024', max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.CharField(blank=True, help_text='Например: Скидка на летние перевозки', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_percent',
            field=models.PositiveIntegerField(help_text='Размер скидки в процентах (от 1 до 100)', verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отключите, чтобы временно заблокировать промокод', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_from',
            field=models.DateField(help_text='Дата начала действия промокода', verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_to',
            field=models.DateField(help_text='Дата окончания действия промокода', verbose_name='Действует по'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Ужасно'), (2, '2 - Плохо'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(help_text='Обязанности, требования, условия работы', verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снять галочку, если вакансия закрыта', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, help_text='Например: от 1500 руб. или договорная', max_length=100, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='cargohandling.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity_kg',
            field=models.PositiveIntegerField(verbose_name='Грузоподъемность, кг'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargohandling.vehicletype', verbose_name='Вид ТС'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Вид транспортного средства'),
        ),
    ]
